# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dataMonitorUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import pandas as pd

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):

        data = pd.read_csv("data/data.csv")
        list = data.values.tolist()

        Frame.setObjectName("Frame")
        Frame.resize(998, 480)
        self.tableWidget = QtWidgets.QTableWidget(Frame)
        self.tableWidget.setGeometry(QtCore.QRect(100, 40, 841, 381))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(len(list))

        for i in range(len(list)):
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setVerticalHeaderItem(i, item)
            for j in range(len(list[i])):
                # print(str(i) + "----" + str(list[i][j]) )
                item = QtWidgets.QTableWidgetItem()
                self.tableWidget.setHorizontalHeaderItem(0, item)
                item = QtWidgets.QTableWidgetItem()

                self.tableWidget.setColumnWidth(0, 200)

                self.tableWidget.setHorizontalHeaderItem(1, item)
                item = QtWidgets.QTableWidgetItem()
                self.tableWidget.setHorizontalHeaderItem(2, item)
                item = QtWidgets.QTableWidgetItem()
                self.tableWidget.setHorizontalHeaderItem(3, item)
                item = QtWidgets.QTableWidgetItem()

                self.tableWidget.setItem(i, 0, item)
                item = QtWidgets.QTableWidgetItem()
                self.tableWidget.setItem(i, 1, item)
                item = QtWidgets.QTableWidgetItem()
                self.tableWidget.setItem(i, 2, item)
                item = QtWidgets.QTableWidgetItem()
                self.tableWidget.setItem(i, 3, item)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Frame", "1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Frame", "时间"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Frame", "温度"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Frame", "湿度"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Frame", "二氧化碳浓度"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)

        data = pd.read_csv("data/data.csv")
        list = data.values.tolist()
        for i in range(len(list)):
            # print(str(i) + "----" + str(list[i][2]) )
            item = self.tableWidget.verticalHeaderItem(i)
            item.setText(_translate("Frame", str(i)))
            item = self.tableWidget.item(i, 0)
            item.setText(_translate("Frame", str(list[i][2])))
            item = self.tableWidget.item(i, 1)
            item.setText(_translate("Frame", str(list[i][3])))
            item = self.tableWidget.item(i, 2)
            item.setText(_translate("Frame", str(list[i][4])))
            item = self.tableWidget.item(i, 3)
            item.setText(_translate("Frame", str(list[i][5])))

        self.tableWidget.setSortingEnabled(__sortingEnabled)
